on: [push, pull_request]
name: aws
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: List files in S3 bucket
      run: aws s3 ls s3://aws-cli-gh-action-test
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
